"use client";
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import './styles.css'

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const navLinks = [
    { href: '/', label: 'Home' },
    { href: '/docs', label: 'Docs' },
    { href: '/products', label: 'Products' },
    { href: '/dashboard', label: 'dashboard' },
  ];
  const pathname = usePathname();
  return (
    <html lang="en">
      <body>
        <header style={
          {
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            padding: '1rem',
            borderBottom: '1px solid #ccc',
          }
        }>
          {navLinks.map((links) => {
            const isActive = pathname.startsWith(links.href);
            return (
              <Link href={links.href} key={links.href}
              className= {isActive ? 'font-bold mr-4' : 'text-blue-500 mr-4'}
              >
                {links.label}
              </Link>
            )
          })}
        </header>
        {children}
        <footer style={{
          position: 'fixed',
          bottom: 0,
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          padding: '1rem',
          borderTop: '1px solid #ccc',
        }}>
          <h1>Footer</h1>
          </footer>
      </body>
    </html>
  )
}